apiVersion: apps/v1                # Corrected apiVersion
kind: Deployment
metadata:
  name: two-tier-app               # Removed the dash to make it a map
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:                        # Corrected the selector field
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: atharva038/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.110.251.77"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

